### ISSUE TITLE
some error happend 

### ISSUE THREAD

**Issue by cjf9028** [mstrise/dep2label#2]
Learning rate is set as: 0.02
Traceback (most recent call last):
  File "main.py", line 476, in <module>
    train(train_data,decode,args)
  File "main.py", line 314, in train
    instance, data.HP_gpu)
  File "main.py", line 225, in batchify_with_label
    mask[idx, :seqlen] = torch.Tensor([1] * seqlen)
TypeError: mul(): argument 'other' (position 1) must be Tensor, not list

how to solve it

**Comment by mstrise** [comment]
Hi! 

Thanks for the interest in our project. I need some more information in order to find out where that bug comes from. 
Just committed an issue template you can find [here](https://github.com/mstrise/dep2label/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

Could you please edit your message so as to conform to the new template so that I can more easily figure out what went wrong?

**Comment by cjf9028** [comment]
my dataset like this 

1	La	_	DET	DET	_	2	det	_	_
2	construcción	_	NOUN	NOUN	_	11	nsubj	_	_
3	de	_	ADP	ADP	_	5	adp	_	_
4	la	_	DET	DET	_	5	det	_	_

and use glove 6b 30d

 python main.py --train-config config/train.config --decode-config config/decode.config

**Comment by cjf9028** [comment]
Are you able to run the usage commands from the README.md by following the exact instructions? 
Yes

Describe the bug A clear and concise description of what the bug is.

To Reproduce Steps to reproduce the behavior:

1	La	_	DET	DET	_	2	det	_	_
2	construcción	_	NOUN	NOUN	_	11	nsubj	_	_
3	de	_	ADP	ADP	_	5	adp	_	_
4	la	_	DET	DET	_	5	det	_	_

and use glove 6b 30d

Run this command  python main.py --train-config config/train.config --decode-config config/decode.config

See error

Learning rate is set as: 0.02
Traceback (most recent call last):
File "main.py", line 476, in 
train(train_data,decode,args)
File "main.py", line 314, in train
instance, data.HP_gpu)
File "main.py", line 225, in batchify_with_label
mask[idx, :seqlen] = torch.Tensor([1] * seqlen)
TypeError: mul(): argument 'other' (position 1) must be Tensor, not list

OS: [Ubuntu 16.04]
Python version [e.g. 2.7]
Pytorch version [e.g. 0.3]
Additional context Add any other context about the problem here.

**Comment by mstrise** [comment]
It can be related to the PyTorch version you use. Which one is it? It should be 0.3.

**Comment by cjf9028** [comment]
oh i install wrong version 
after change version working
